# This is the customized yaml. Replace the item with pre-design modules to reach diverse settings.

defaults:
  - test_scenario: demo_loop  # The name of the script
  - world: sunny  # The weather is no working for OpenScenario